import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

# Set up GPIO pins
MOTOR_LEFT_FORWARD = 20
MOTOR_LEFT_BACKWARD = 21
MOTOR_RIGHT_FORWARD = 16
MOTOR_RIGHT_BACKWARD = 12

# Set up motor pins as outputs
GPIO.setup(MOTOR_LEFT_FORWARD, GPIO.OUT)
GPIO.setup(MOTOR_LEFT_BACKWARD, GPIO.OUT)
GPIO.setup(MOTOR_RIGHT_FORWARD, GPIO.OUT)
GPIO.setup(MOTOR_RIGHT_BACKWARD, GPIO.OUT)

# Turn on the motors
GPIO.output(MOTOR_LEFT_FORWARD, GPIO.HIGH)
GPIO.output(MOTOR_LEFT_BACKWARD, GPIO.LOW)
GPIO.output(MOTOR_RIGHT_FORWARD, GPIO.HIGH)
GPIO.output(MOTOR_RIGHT_BACKWARD, GPIO.LOW)

# Wait for 2 seconds
time.sleep(2)

# Turn off the motors
GPIO.output(MOTOR_LEFT_FORWARD, GPIO.LOW)
GPIO.output(MOTOR_LEFT_BACKWARD, GPIO.HIGH)
GPIO.output(MOTOR_RIGHT_FORWARD, GPIO.LOW)
GPIO.output(MOTOR_RIGHT_BACKWARD, GPIO.HIGH)

# Clean up GPIO pins when done
GPIO.cleanup()
